// Static agricultural data layer for Kenya
// Based on KALRO crop calendars, agro-ecological zones, and rainfall patterns

export type County = {
  name: string;
  region: 'Rift Valley' | 'Western' | 'Central' | 'Eastern' | 'Coast' | 'Nyanza' | 'Nairobi';
  subCounties: string[];
  latitude: number;
  longitude: number;
  agroEcologicalZone: string;
  rainfallZone: 'High' | 'Medium' | 'Low';
  annualRainfallMm: number;
  longRainsStart: string; // 'Mar' | 'Apr'
  longRainsEnd: string;
  shortRainsStart: string; // 'Oct' | 'Nov'
  shortRainsEnd: string;
};

export const COUNTIES: County[] = [
  {
    name: 'Nakuru',
    region: 'Rift Valley',
    subCounties: ['Gilgil', 'Naivasha', 'Nakuru Town', 'Molo', 'Kuresoi', 'Subukia', 'Rongai'],
    latitude: -0.3031,
    longitude: 36.08,
    agroEcologicalZone: 'Highland (LH2)',
    rainfallZone: 'Medium',
    annualRainfallMm: 950,
    longRainsStart: 'Mar',
    longRainsEnd: 'May',
    shortRainsStart: 'Oct',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Kisumu',
    region: 'Nyanza',
    subCounties: ['Kisumu East', 'Kisumu West', 'Nyando', 'Muhoroni', 'Nyakach'],
    latitude: -0.0917,
    longitude: 34.768,
    agroEcologicalZone: 'Lower Midland (LM1)',
    rainfallZone: 'High',
    annualRainfallMm: 1200,
    longRainsStart: 'Mar',
    longRainsEnd: 'May',
    shortRainsStart: 'Sep',
    shortRainsEnd: 'Nov',
  },
  {
    name: 'Kakamega',
    region: 'Western',
    subCounties: ['Kakamega Town', 'Lurambi', 'Mumias', 'Lugari', 'Shinyalu', 'Ikolomani'],
    latitude: 0.2827,
    longitude: 34.7519,
    agroEcologicalZone: 'Upper Midland (UM1)',
    rainfallZone: 'High',
    annualRainfallMm: 1800,
    longRainsStart: 'Mar',
    longRainsEnd: 'Jun',
    shortRainsStart: 'Sep',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Kiambu',
    region: 'Central',
    subCounties: ['Kiambu Town', 'Ruiru', 'Thika', 'Limuru', 'Kikuyu', 'Gatundu', 'Lari'],
    latitude: -1.1714,
    longitude: 36.8356,
    agroEcologicalZone: 'Upper Midland (UM2)',
    rainfallZone: 'Medium',
    annualRainfallMm: 1100,
    longRainsStart: 'Mar',
    longRainsEnd: 'May',
    shortRainsStart: 'Oct',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Meru',
    region: 'Central',
    subCounties: ['Meru Town', 'North Imenti', 'South Imenti', 'Igembe', 'Tigania', 'Buuri'],
    latitude: 0.0469,
    longitude: 37.6547,
    agroEcologicalZone: 'Upper Midland (UM2)',
    rainfallZone: 'High',
    annualRainfallMm: 1300,
    longRainsStart: 'Mar',
    longRainsEnd: 'May',
    shortRainsStart: 'Oct',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Machakos',
    region: 'Eastern',
    subCounties: ['Machakos Town', 'Mavoko', 'Kangundo', 'Kathiani', 'Yatta', 'Mwala'],
    latitude: -1.5167,
    longitude: 37.2667,
    agroEcologicalZone: 'Lower Midland (LM4)',
    rainfallZone: 'Low',
    annualRainfallMm: 700,
    longRainsStart: 'Mar',
    longRainsEnd: 'May',
    shortRainsStart: 'Oct',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Kitui',
    region: 'Eastern',
    subCounties: ['Kitui Town', 'Kitui Central', 'Mutomo', 'Mwingi', 'Tseikuru'],
    latitude: -1.3792,
    longitude: 38.0106,
    agroEcologicalZone: 'Lower Midland (LM5)',
    rainfallZone: 'Low',
    annualRainfallMm: 600,
    longRainsStart: 'Mar',
    longRainsEnd: 'May',
    shortRainsStart: 'Oct',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Bungoma',
    region: 'Western',
    subCounties: ['Bungoma Town', 'Kanduyi', 'Webuye', 'Kimilili', 'Tongaren', 'Mt Elgon'],
    latitude: 0.5635,
    longitude: 34.5606,
    agroEcologicalZone: 'Upper Midland (UM2)',
    rainfallZone: 'High',
    annualRainfallMm: 1600,
    longRainsStart: 'Mar',
    longRainsEnd: 'Jun',
    shortRainsStart: 'Sep',
    shortRainsEnd: 'Nov',
  },
  {
    name: 'Trans Nzoia',
    region: 'Rift Valley',
    subCounties: ['Kitale', 'Kiminini', 'Cherangany', 'Saboti', 'Kwanza', 'Endebess'],
    latitude: 1.0215,
    longitude: 34.7739,
    agroEcologicalZone: 'Upper Midland (UM1)',
    rainfallZone: 'High',
    annualRainfallMm: 1400,
    longRainsStart: 'Mar',
    longRainsEnd: 'Jun',
    shortRainsStart: 'Sep',
    shortRainsEnd: 'Nov',
  },
  {
    name: 'Uasin Gishu',
    region: 'Rift Valley',
    subCounties: ['Eldoret', 'Kesses', 'Ainabkoi', 'Moiben', 'Soy', 'Turbo'],
    latitude: 0.5143,
    longitude: 35.2758,
    agroEcologicalZone: 'Highland (LH3)',
    rainfallZone: 'Medium',
    annualRainfallMm: 1100,
    longRainsStart: 'Mar',
    longRainsEnd: 'Jun',
    shortRainsStart: 'Oct',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Mombasa',
    region: 'Coast',
    subCounties: ['Mombasa Island', 'Nyali', 'Likoni', 'Kisauni', 'Changamwe', 'Jomvu'],
    latitude: -4.0435,
    longitude: 39.6682,
    agroEcologicalZone: 'Coastal Lowland (CL3)',
    rainfallZone: 'Low',
    annualRainfallMm: 900,
    longRainsStart: 'Apr',
    longRainsEnd: 'Jun',
    shortRainsStart: 'Oct',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Kilifi',
    region: 'Coast',
    subCounties: ['Kilifi Town', 'Bahari', 'Ganze', 'Kaloleni', 'Malindi', 'Magarini'],
    latitude: -3.6333,
    longitude: 39.85,
    agroEcologicalZone: 'Coastal Lowland (CL4)',
    rainfallZone: 'Low',
    annualRainfallMm: 800,
    longRainsStart: 'Apr',
    longRainsEnd: 'Jun',
    shortRainsStart: 'Oct',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Nairobi',
    region: 'Nairobi',
    subCounties: ['Westlands', 'Dagoretti', 'Embakasi', 'Kasarani', 'Langata', 'Makadara'],
    latitude: -1.2864,
    longitude: 36.8172,
    agroEcologicalZone: 'Upper Midland (UM3)',
    rainfallZone: 'Medium',
    annualRainfallMm: 900,
    longRainsStart: 'Mar',
    longRainsEnd: 'May',
    shortRainsStart: 'Oct',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Nyeri',
    region: 'Central',
    subCounties: ['Nyeri Town', 'Othaya', 'Mukurweini', 'Mathira', 'Kieni', 'Tetu'],
    latitude: -0.4167,
    longitude: 36.95,
    agroEcologicalZone: 'Highland (LH2)',
    rainfallZone: 'Medium',
    annualRainfallMm: 1000,
    longRainsStart: 'Mar',
    longRainsEnd: 'May',
    shortRainsStart: 'Oct',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Embu',
    region: 'Eastern',
    subCounties: ['Embu Town', 'Manyatta', 'Runyenjes', 'Mbeere North', 'Mbeere South'],
    latitude: -0.5321,
    longitude: 37.4506,
    agroEcologicalZone: 'Upper Midland (UM2)',
    rainfallZone: 'Medium',
    annualRainfallMm: 950,
    longRainsStart: 'Mar',
    longRainsEnd: 'May',
    shortRainsStart: 'Oct',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Homa Bay',
    region: 'Nyanza',
    subCounties: ['Homa Bay Town', 'Rangwe', 'Ndhiwa', 'Mbita', 'Rachuonyo', 'Kasipul'],
    latitude: -0.5277,
    longitude: 34.4561,
    agroEcologicalZone: 'Lower Midland (LM2)',
    rainfallZone: 'Medium',
    annualRainfallMm: 950,
    longRainsStart: 'Mar',
    longRainsEnd: 'May',
    shortRainsStart: 'Sep',
    shortRainsEnd: 'Nov',
  },
  {
    name: 'Murang\'a',
    region: 'Central',
    subCounties: ['Murang\'a Town', 'Kiharu', 'Kangema', 'Mathioya', 'Kigumo', 'Gatanga'],
    latitude: -0.7167,
    longitude: 37.15,
    agroEcologicalZone: 'Upper Midland (UM1)',
    rainfallZone: 'High',
    annualRainfallMm: 1300,
    longRainsStart: 'Mar',
    longRainsEnd: 'May',
    shortRainsStart: 'Oct',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Kericho',
    region: 'Rift Valley',
    subCounties: ['Kericho Town', 'Ainamoi', 'Buret', 'Kipkelion', 'Belgut', 'Sigowet'],
    latitude: -0.3672,
    longitude: 35.2884,
    agroEcologicalZone: 'Highland (LH1)',
    rainfallZone: 'High',
    annualRainfallMm: 1800,
    longRainsStart: 'Mar',
    longRainsEnd: 'Jun',
    shortRainsStart: 'Sep',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Siaya',
    region: 'Nyanza',
    subCounties: ['Siaya Town', 'Bondo', 'Rarieda', 'Alego', 'Ugenya', 'Gem'],
    latitude: 0.0606,
    longitude: 34.2886,
    agroEcologicalZone: 'Lower Midland (LM2)',
    rainfallZone: 'Medium',
    annualRainfallMm: 1000,
    longRainsStart: 'Mar',
    longRainsEnd: 'May',
    shortRainsStart: 'Sep',
    shortRainsEnd: 'Nov',
  },
  {
    name: 'Laikipia',
    region: 'Rift Valley',
    subCounties: ['Rumuruti', 'Nyahururu', 'Laikipia East', 'Laikipia West', 'Laikipia North'],
    latitude: 0.6333,
    longitude: 36.8333,
    agroEcologicalZone: 'Highland (LH3)',
    rainfallZone: 'Low',
    annualRainfallMm: 700,
    longRainsStart: 'Mar',
    longRainsEnd: 'May',
    shortRainsStart: 'Oct',
    shortRainsEnd: 'Dec',
  },
  {
    name: 'Makueni',
    region: 'Eastern',
    subCounties: ['Makueni Town', 'Kibwezi', 'Kilome', 'Mbooni', 'Nzaui', 'Kaiti'],
    latitude: -1.8,
    longitude: 37.6333,
    agroEcologicalZone: 'Lower Midland (LM5)',
    rainfallZone: 'Low',
    annualRainfallMm: 600,
    longRainsStart: 'Mar',
    longRainsEnd: 'May',
    shortRainsStart: 'Oct',
    shortRainsEnd: 'Dec',
  },
];

export type CropInfo = {
  name: string;
  emoji: string;
  category: 'cereal' | 'legume' | 'tuber' | 'cash' | 'vegetable';
  // Maturity in days for standard varieties
  maturityDays: number;
  // Suitable rainfall range mm/season
  minRainfall: number;
  maxRainfall: number;
  // Suitable agro-ecological zones (keywords)
  zones: string[];
  // Long rains (LR) or short rains (SR) preference
  seasons: ('LR' | 'SR')[];
  // Varieties with maturity in days
  varieties: { name: string; maturityDays: number; type: 'short' | 'medium' | 'long'; notes: string }[];
  // Growth stages with day ranges (relative to planting)
  stages: { name: string; startDay: number; endDay: number; description: string }[];
  // Weekly activity template keyed by week number
  weeklyActivities: { week: number; title: string; description: string; category: string }[];
};

export const CROPS: CropInfo[] = [
  {
    name: 'Maize',
    emoji: '🌽',
    category: 'cereal',
    maturityDays: 120,
    minRainfall: 400,
    maxRainfall: 1200,
    zones: ['Highland', 'Upper Midland', 'Lower Midland'],
    seasons: ['LR', 'SR'],
    varieties: [
      { name: 'H614', maturityDays: 140, type: 'long', notes: 'Highland variety, high yield, needs 140+ days' },
      { name: 'H621', maturityDays: 135, type: 'long', notes: 'Highland, good for high rainfall zones' },
      { name: 'DK777', maturityDays: 120, type: 'medium', notes: 'Mid-altitude, widely adapted' },
      { name: 'DK8053', maturityDays: 118, type: 'medium', notes: 'Drought tolerant, mid-altitude' },
      { name: 'WH403', maturityDays: 90, type: 'short', notes: 'Short maturity, good for late planting or short rains' },
      { name: 'WH507', maturityDays: 95, type: 'short', notes: 'Short season, drought escape' },
      { name: 'Pannar 4M-21', maturityDays: 100, type: 'short', notes: 'Early maturing, low rainfall areas' },
    ],
    stages: [
      { name: 'Germination', startDay: 0, endDay: 7, description: 'Seed sprouts, first roots and shoot emerge' },
      { name: 'Seedling', startDay: 8, endDay: 21, description: 'Leaves develop, plant establishes' },
      { name: 'Vegetative', startDay: 22, endDay: 45, description: 'Rapid stem and leaf growth' },
      { name: 'Tasseling', startDay: 46, endDay: 60, description: 'Flowering begins, pollen shed' },
      { name: 'Silking', startDay: 61, endDay: 75, description: 'Silks emerge, pollination occurs' },
      { name: 'Grain filling', startDay: 76, endDay: 105, description: 'Kernels develop and fill' },
      { name: 'Physiological maturity', startDay: 106, endDay: 120, description: 'Black layer forms, ready to harvest' },
    ],
    weeklyActivities: [
      { week: 1, title: 'Monitor emergence', description: 'Check for uniform germination. Replant gaps within 7 days.', category: 'monitoring' },
      { week: 2, title: 'First weeding', description: 'Hand weed to reduce competition. Maize is very sensitive to early weed pressure.', category: 'weeding' },
      { week: 3, title: 'Apply basal fertilizer (DAP)', description: 'Apply DAP/CAN at 2-3 weeks after planting when plants are 15-20cm tall.', category: 'fertilizer' },
      { week: 4, title: 'Top dress with CAN', description: 'Top dress with CAN at 4-5 weeks when plants reach knee height.', category: 'fertilizer' },
      { week: 5, title: 'Second weeding', description: 'Weed again before canopy closes. Hilling up soil around stems.', category: 'weeding' },
      { week: 6, title: 'Scout for Fall Armyworm', description: 'Inspect whorls for Fall Armyworm damage. Spray if threshold exceeded.', category: 'pest' },
      { week: 7, title: 'Scout for stalk borer', description: 'Look for shot-holes on leaves. Apply control if infestation severe.', category: 'pest' },
      { week: 8, title: 'Monitor moisture', description: 'Critical tasseling stage. Ensure adequate soil moisture.', category: 'monitoring' },
      { week: 10, title: 'Top dress (late)', description: 'Final top dress if leaves yellowing. Avoid after tasseling.', category: 'fertilizer' },
      { week: 12, title: 'Scout for lodging', description: 'Check for stem lodging. Hill up if needed.', category: 'monitoring' },
      { week: 14, title: 'Bird scaring', description: 'Start bird scaring as grain hardens. Watch for weevils.', category: 'pest' },
      { week: 16, title: 'Harvest preparation', description: 'Check black layer formation. Prepare drying space.', category: 'harvest' },
    ],
  },
  {
    name: 'Beans',
    emoji: '🫘',
    category: 'legume',
    maturityDays: 75,
    minRainfall: 300,
    maxRainfall: 900,
    zones: ['Highland', 'Upper Midland', 'Lower Midland', 'Coastal Lowland'],
    seasons: ['LR', 'SR'],
    varieties: [
      { name: 'Rosecoco', maturityDays: 80, type: 'medium', notes: 'Popular, good market demand' },
      { name: 'Wairimu', maturityDays: 75, type: 'medium', notes: 'Red variety, disease resistant' },
      { name: 'Mwitemania', maturityDays: 70, type: 'short', notes: 'Drought tolerant, low rainfall areas' },
      { name: 'KAT B1', maturityDays: 65, type: 'short', notes: 'Early maturing, short rains' },
      { name: 'KAT B9', maturityDays: 68, type: 'short', notes: 'Drought escape, good for marginal areas' },
      { name: 'Chelal', maturityDays: 75, type: 'medium', notes: 'Climbing bean, high yield' },
    ],
    stages: [
      { name: 'Germination', startDay: 0, endDay: 5, description: 'Seed absorbs water, radicle emerges' },
      { name: 'Seedling', startDay: 6, endDay: 15, description: 'Unifoliate leaves unfold' },
      { name: 'Vegetative', startDay: 16, endDay: 30, description: 'Trifoliate leaves, branching' },
      { name: 'Flowering', startDay: 31, endDay: 45, description: 'Flowers open, pollination' },
      { name: 'Pod fill', startDay: 46, endDay: 65, description: 'Pods develop, seeds fill' },
      { name: 'Maturity', startDay: 66, endDay: 75, description: 'Pods yellow, ready to harvest' },
    ],
    weeklyActivities: [
      { week: 1, title: 'Monitor emergence', description: 'Check germination. Inoculate with rhizobium if not done.', category: 'monitoring' },
      { week: 2, title: 'First weeding', description: 'Hand weed carefully. Beans are shallow-rooted.', category: 'weeding' },
      { week: 3, title: 'Top dress (optional)', description: 'Apply small CAN if leaves yellow. Beans fix own N.', category: 'fertilizer' },
      { week: 4, title: 'Scout for aphids', description: 'Check for aphids and bean fly. Spray if needed.', category: 'pest' },
      { week: 5, title: 'Second weeding', description: 'Final weed before flowering.', category: 'weeding' },
      { week: 6, title: 'Scout for rust', description: 'Look for rust pustules on leaves. Apply fungicide if severe.', category: 'pest' },
      { week: 8, title: 'Scout for pod borers', description: 'Check pods for borers. Control if threshold exceeded.', category: 'pest' },
      { week: 10, title: 'Harvest preparation', description: 'Stop spraying. Watch for pod yellowing.', category: 'harvest' },
      { week: 11, title: 'Harvest', description: 'Harvest when pods dry. Thresh and dry to 13% moisture.', category: 'harvest' },
    ],
  },
  {
    name: 'Sorghum',
    emoji: '🌾',
    category: 'cereal',
    maturityDays: 105,
    minRainfall: 250,
    maxRainfall: 800,
    zones: ['Lower Midland', 'Coastal Lowland', 'Upper Midland'],
    seasons: ['LR', 'SR'],
    varieties: [
      { name: 'Gadam', maturityDays: 90, type: 'short', notes: 'Early maturing, drought tolerant' },
      { name: 'Serendo', maturityDays: 105, type: 'medium', notes: 'Dual purpose, grain + fodder' },
      { name: 'Sila', maturityDays: 100, type: 'medium', notes: 'Good for semi-arid areas' },
      { name: 'Kari/Mtama-1', maturityDays: 110, type: 'medium', notes: 'High yielding, bird resistant' },
      { name: 'E117', maturityDays: 115, type: 'long', notes: 'Late maturity, high rainfall areas' },
    ],
    stages: [
      { name: 'Germination', startDay: 0, endDay: 6, description: 'Seed sprouts' },
      { name: 'Seedling', startDay: 7, endDay: 20, description: 'Establishment' },
      { name: 'Vegetative', startDay: 21, endDay: 50, description: 'Rapid growth' },
      { name: 'Panicle initiation', startDay: 51, endDay: 65, description: 'Flower head forms' },
      { name: 'Flowering', startDay: 66, endDay: 80, description: 'Anthesis' },
      { name: 'Grain fill', startDay: 81, endDay: 100, description: 'Grains develop' },
      { name: 'Maturity', startDay: 101, endDay: 105, description: 'Ready to harvest' },
    ],
    weeklyActivities: [
      { week: 1, title: 'Monitor emergence', description: 'Check plant population. Thin if crowded.', category: 'monitoring' },
      { week: 2, title: 'First weeding', description: 'Hand weed. Sorghum sensitive to early competition.', category: 'weeding' },
      { week: 3, title: 'Top dress with CAN', description: 'Apply CAN at 3-4 weeks after emergence.', category: 'fertilizer' },
      { week: 4, title: 'Scout for shoot fly', description: 'Look for dead hearts. Apply control if needed.', category: 'pest' },
      { week: 5, title: 'Second weeding', description: 'Weed before stem elongation.', category: 'weeding' },
      { week: 6, title: 'Scout for stem borer', description: 'Check for stem borer damage.', category: 'pest' },
      { week: 8, title: 'Bird scaring', description: 'Start bird scaring during grain fill.', category: 'pest' },
      { week: 10, title: 'Monitor maturity', description: 'Check for black layer on grains.', category: 'harvest' },
      { week: 14, title: 'Harvest', description: 'Harvest when grains hard. Dry to 12% moisture.', category: 'harvest' },
    ],
  },
  {
    name: 'Millets',
    emoji: '🌾',
    category: 'cereal',
    maturityDays: 80,
    minRainfall: 200,
    maxRainfall: 600,
    zones: ['Lower Midland', 'Coastal Lowland'],
    seasons: ['LR', 'SR'],
    varieties: [
      { name: 'KAT/PM1', maturityDays: 75, type: 'short', notes: 'Early pearl millet' },
      { name: 'Serere 4A', maturityDays: 80, type: 'short', notes: 'Finger millet, good for brewing' },
      { name: 'P224', maturityDays: 85, type: 'medium', notes: 'Finger millet, high yielding' },
      { name: 'U-15', maturityDays: 90, type: 'medium', notes: 'Finger millet, blast resistant' },
    ],
    stages: [
      { name: 'Germination', startDay: 0, endDay: 5, description: 'Seed sprouts' },
      { name: 'Seedling', startDay: 6, endDay: 18, description: 'Establishment' },
      { name: 'Vegetative', startDay: 19, endDay: 45, description: 'Tillering' },
      { name: 'Flowering', startDay: 46, endDay: 60, description: 'Head emergence' },
      { name: 'Grain fill', startDay: 61, endDay: 75, description: 'Grains develop' },
      { name: 'Maturity', startDay: 76, endDay: 80, description: 'Ready to harvest' },
    ],
    weeklyActivities: [
      { week: 1, title: 'Monitor emergence', description: 'Check germination. Thin to 10cm spacing.', category: 'monitoring' },
      { week: 2, title: 'First weeding', description: 'Hand weed carefully.', category: 'weeding' },
      { week: 4, title: 'Top dress', description: 'Apply small CAN if needed.', category: 'fertilizer' },
      { week: 5, title: 'Second weeding', description: 'Final weed before heading.', category: 'weeding' },
      { week: 6, title: 'Scout for blast', description: 'Look for neck blast on finger millet.', category: 'pest' },
      { week: 8, title: 'Bird scaring', description: 'Birds love millet. Start scaring.', category: 'pest' },
      { week: 11, title: 'Harvest', description: 'Harvest when heads turn brown.', category: 'harvest' },
    ],
  },
  {
    name: 'Cowpeas',
    emoji: '🫛',
    category: 'legume',
    maturityDays: 70,
    minRainfall: 200,
    maxRainfall: 700,
    zones: ['Lower Midland', 'Coastal Lowland', 'Upper Midland'],
    seasons: ['LR', 'SR'],
    varieties: [
      { name: 'K80', maturityDays: 70, type: 'medium', notes: 'Dual purpose, grain + leaves' },
      { name: 'M66', maturityDays: 65, type: 'short', notes: 'Early, drought tolerant' },
      { name: 'Katumani 1', maturityDays: 68, type: 'short', notes: 'Semi-arid areas' },
      { name: 'Macuita', maturityDays: 75, type: 'medium', notes: 'Spreading type, good for fodder' },
    ],
    stages: [
      { name: 'Germination', startDay: 0, endDay: 4, description: 'Seed sprouts' },
      { name: 'Seedling', startDay: 5, endDay: 14, description: 'Establishment' },
      { name: 'Vegetative', startDay: 15, endDay: 35, description: 'Vines spread' },
      { name: 'Flowering', startDay: 36, endDay: 50, description: 'Flowers open' },
      { name: 'Pod fill', startDay: 51, endDay: 65, description: 'Pods fill' },
      { name: 'Maturity', startDay: 66, endDay: 70, description: 'Ready to harvest' },
    ],
    weeklyActivities: [
      { week: 1, title: 'Monitor emergence', description: 'Check germination.', category: 'monitoring' },
      { week: 2, title: 'First weeding', description: 'Hand weed.', category: 'weeding' },
      { week: 4, title: 'Scout for aphids', description: 'Check for aphids. Spray if needed.', category: 'pest' },
      { week: 5, title: 'Second weeding', description: 'Weed before flowering.', category: 'weeding' },
      { week: 6, title: 'Scout for pod borers', description: 'Check pods for borers.', category: 'pest' },
      { week: 9, title: 'Harvest', description: 'Harvest green leaves for vegetable. Dry grain at 12% moisture.', category: 'harvest' },
    ],
  },
  {
    name: 'Green Grams',
    emoji: '🫛',
    category: 'legume',
    maturityDays: 65,
    minRainfall: 250,
    maxRainfall: 600,
    zones: ['Lower Midland', 'Coastal Lowland'],
    seasons: ['LR', 'SR'],
    varieties: [
      { name: 'KS20', maturityDays: 65, type: 'short', notes: 'Early, drought tolerant' },
      { name: 'Biashara', maturityDays: 70, type: 'medium', notes: 'Popular market variety' },
      { name: 'N26', maturityDays: 68, type: 'short', notes: 'Good for short rains' },
    ],
    stages: [
      { name: 'Germination', startDay: 0, endDay: 4, description: 'Seed sprouts' },
      { name: 'Seedling', startDay: 5, endDay: 14, description: 'Establishment' },
      { name: 'Vegetative', startDay: 15, endDay: 30, description: 'Growth' },
      { name: 'Flowering', startDay: 31, endDay: 45, description: 'Flowers open' },
      { name: 'Pod fill', startDay: 46, endDay: 60, description: 'Pods fill' },
      { name: 'Maturity', startDay: 61, endDay: 65, description: 'Ready to harvest' },
    ],
    weeklyActivities: [
      { week: 1, title: 'Monitor emergence', description: 'Check germination.', category: 'monitoring' },
      { week: 2, title: 'First weeding', description: 'Hand weed.', category: 'weeding' },
      { week: 4, title: 'Scout for aphids', description: 'Check for aphids.', category: 'pest' },
      { week: 5, title: 'Second weeding', description: 'Weed before flowering.', category: 'weeding' },
      { week: 6, title: 'Scout for pod borers', description: 'Check pods.', category: 'pest' },
      { week: 8, title: 'Harvest', description: 'Harvest when pods turn dark. Dry to 12% moisture.', category: 'harvest' },
    ],
  },
  {
    name: 'Sweet Potato',
    emoji: '🍠',
    category: 'tuber',
    maturityDays: 110,
    minRainfall: 500,
    maxRainfall: 1200,
    zones: ['Highland', 'Upper Midland', 'Lower Midland', 'Coastal Lowland'],
    seasons: ['LR', 'SR'],
    varieties: [
      { name: 'KSP20', maturityDays: 110, type: 'medium', notes: 'Orange flesh, high vitamin A' },
      { name: 'Kemb 10', maturityDays: 120, type: 'long', notes: 'High yielding, white flesh' },
      { name: 'Zapallo', maturityDays: 100, type: 'medium', notes: 'Orange flesh, early' },
      { name: 'SPK004', maturityDays: 105, type: 'medium', notes: 'Drought tolerant' },
    ],
    stages: [
      { name: 'Establishment', startDay: 0, endDay: 14, description: 'Vines root and establish' },
      { name: 'Vine growth', startDay: 15, endDay: 45, description: 'Rapid vine growth' },
      { name: 'Tuber initiation', startDay: 46, endDay: 60, description: 'Tubers begin to form' },
      { name: 'Tuber bulking', startDay: 61, endDay: 100, description: 'Tubers enlarge' },
      { name: 'Maturity', startDay: 101, endDay: 110, description: 'Ready to harvest' },
    ],
    weeklyActivities: [
      { week: 1, title: 'Monitor establishment', description: 'Check vine rooting. Water if dry.', category: 'monitoring' },
      { week: 2, title: 'First weeding', description: 'Hand weed around vines.', category: 'weeding' },
      { week: 4, title: 'Hilling up', description: 'Mound soil around base for tuber development.', category: 'weeding' },
      { week: 6, title: 'Second weeding', description: 'Weed before vines cover ground.', category: 'weeding' },
      { week: 8, title: 'Scout for weevils', description: 'Check for sweet potato weevil damage.', category: 'pest' },
      { week: 10, title: 'Top dress', description: 'Apply potash if leaves yellow.', category: 'fertilizer' },
      { week: 14, title: 'Harvest preparation', description: 'Start sampling tubers for size.', category: 'harvest' },
      { week: 16, title: 'Harvest', description: 'Harvest carefully to avoid bruising.', category: 'harvest' },
    ],
  },
  {
    name: 'Potato',
    emoji: '🥔',
    category: 'tuber',
    maturityDays: 90,
    minRainfall: 500,
    maxRainfall: 1200,
    zones: ['Highland', 'Upper Midland'],
    seasons: ['LR', 'SR'],
    varieties: [
      { name: 'Shangi', maturityDays: 90, type: 'medium', notes: 'Popular Kenyan variety, good yield' },
      { name: 'Sherekea', maturityDays: 85, type: 'short', notes: 'Early maturity, disease resistant' },
      { name: 'Kenya Karibu', maturityDays: 95, type: 'medium', notes: 'High yielding, widely adapted' },
      { name: 'Asante', maturityDays: 100, type: 'long', notes: 'Late maturity, large tubers' },
      { name: 'Unica', maturityDays: 80, type: 'short', notes: 'Early, drought tolerant' },
    ],
    stages: [
      { name: 'Sprouting', startDay: 0, endDay: 7, description: 'Seed tubers sprout, first shoots emerge' },
      { name: 'Vegetative', startDay: 8, endDay: 27, description: 'Leaves and stems develop, canopy forms' },
      { name: 'Tuber initiation', startDay: 28, endDay: 45, description: 'Stolons swell, tubers begin to form' },
      { name: 'Tuber bulking', startDay: 46, endDay: 77, description: 'Tubers enlarge and accumulate starch' },
      { name: 'Maturation', startDay: 78, endDay: 90, description: 'Vines yellow and senesce, skins set' },
    ],
    weeklyActivities: [
      { week: 1, title: 'Monitor sprouting', description: 'Check for uniform emergence. Hill up soil around stems.', category: 'monitoring' },
      { week: 2, title: 'First weeding and hilling', description: 'Hand weed and hill up soil to protect tubers from light.', category: 'weeding' },
      { week: 3, title: 'Top dress with CAN', description: 'Apply CAN at 3-4 weeks after emergence when plants are 15-20cm tall.', category: 'fertilizer' },
      { week: 4, title: 'Scout for late blight', description: 'Inspect leaves for late blight lesions. Spray fungicide if detected.', category: 'pest' },
      { week: 5, title: 'Second hilling', description: 'Final hilling up before canopy closes.', category: 'weeding' },
      { week: 6, title: 'Scout for aphids', description: 'Check for aphids and potato leafroll virus.', category: 'pest' },
      { week: 8, title: 'Monitor tuber development', description: 'Sample plants for tuber size. Ensure adequate moisture.', category: 'monitoring' },
      { week: 10, title: 'Scout for early blight', description: 'Look for early blight concentric rings on lower leaves.', category: 'pest' },
      { week: 12, title: 'Prepare for harvest', description: 'Stop irrigation. Watch for vine senescence and skin set.', category: 'harvest' },
      { week: 13, title: 'Harvest', description: 'Harvest when vines fully senesced. Cure tubers before storage.', category: 'harvest' },
    ],
  },
  {
    name: 'Cassava',
    emoji: '🥔',
    category: 'tuber',
    maturityDays: 300,
    minRainfall: 400,
    maxRainfall: 1500,
    zones: ['Lower Midland', 'Coastal Lowland', 'Upper Midland'],
    seasons: ['LR', 'SR'],
    varieties: [
      { name: 'MH95/0183', maturityDays: 300, type: 'long', notes: 'High yielding, disease resistant' },
      { name: 'Serere', maturityDays: 280, type: 'long', notes: 'Early for cassava' },
      { name: 'KME-1', maturityDays: 320, type: 'long', notes: 'Drought tolerant' },
      { name: 'Tajirika', maturityDays: 300, type: 'long', notes: 'High cyanide, needs processing' },
    ],
    stages: [
      { name: 'Establishment', startDay: 0, endDay: 30, description: 'Cuttings sprout and root' },
      { name: 'Vegetative', startDay: 31, endDay: 120, description: 'Canopy develops' },
      { name: 'Tuber initiation', startDay: 121, endDay: 180, description: 'Tubers form' },
      { name: 'Tuber bulking', startDay: 181, endDay: 280, description: 'Tubers enlarge' },
      { name: 'Maturity', startDay: 281, endDay: 300, description: 'Ready to harvest' },
    ],
    weeklyActivities: [
      { week: 2, title: 'Monitor sprouting', description: 'Check cuttings for sprouting. Replace dead ones.', category: 'monitoring' },
      { week: 4, title: 'First weeding', description: 'Hand weed around plants.', category: 'weeding' },
      { week: 8, title: 'Second weeding', description: 'Weed before canopy closes.', category: 'weeding' },
      { week: 12, title: 'Scout for cassava mosaic', description: 'Look for mosaic symptoms. Rogue affected plants.', category: 'pest' },
      { week: 16, title: 'Scout for cassava brown streak', description: 'Check for brown streak disease.', category: 'pest' },
      { week: 24, title: 'Monitor tuber development', description: 'Sample tubers for size.', category: 'monitoring' },
      { week: 40, title: 'Harvest preparation', description: 'Plan harvest. Cassava can stay in ground.', category: 'harvest' },
    ],
  },
  {
    name: 'Groundnuts',
    emoji: '🥜',
    category: 'legume',
    maturityDays: 100,
    minRainfall: 300,
    maxRainfall: 800,
    zones: ['Lower Midland', 'Upper Midland', 'Coastal Lowland'],
    seasons: ['LR', 'SR'],
    varieties: [
      { name: 'Red Valencia', maturityDays: 100, type: 'medium', notes: 'Popular, red seed' },
      { name: 'Manipintar', maturityDays: 105, type: 'medium', notes: 'Drought tolerant' },
      { name: 'Katse 1', maturityDays: 95, type: 'short', notes: 'Early maturing' },
      { name: 'Bukene', maturityDays: 110, type: 'long', notes: 'High oil content' },
    ],
    stages: [
      { name: 'Germination', startDay: 0, endDay: 7, description: 'Seed sprouts' },
      { name: 'Seedling', startDay: 8, endDay: 20, description: 'Establishment' },
      { name: 'Vegetative', startDay: 21, endDay: 45, description: 'Growth' },
      { name: 'Flowering', startDay: 46, endDay: 60, description: 'Flowers open, pegging' },
      { name: 'Pod fill', startDay: 61, endDay: 90, description: 'Pods develop underground' },
      { name: 'Maturity', startDay: 91, endDay: 100, description: 'Ready to harvest' },
    ],
    weeklyActivities: [
      { week: 1, title: 'Monitor emergence', description: 'Check germination.', category: 'monitoring' },
      { week: 2, title: 'First weeding', description: 'Hand weed carefully.', category: 'weeding' },
      { week: 4, title: 'Gypsum application', description: 'Apply gypsum at pegging for calcium.', category: 'fertilizer' },
      { week: 5, title: 'Second weeding', description: 'Weed before pegging.', category: 'weeding' },
      { week: 6, title: 'Hilling up', description: 'Mound soil to help pegs enter ground.', category: 'weeding' },
      { week: 8, title: 'Scout for rosette', description: 'Look for groundnut rosette virus.', category: 'pest' },
      { week: 12, title: 'Harvest', description: 'Harvest when leaves yellow. Lift carefully.', category: 'harvest' },
    ],
  },
  {
    name: 'Tomato',
    emoji: '🍅',
    category: 'vegetable',
    maturityDays: 90,
    minRainfall: 600,
    maxRainfall: 1200,
    zones: ['Highland', 'Upper Midland', 'Lower Midland'],
    seasons: ['LR', 'SR'],
    varieties: [
      { name: 'Cal-J', maturityDays: 90, type: 'medium', notes: 'Popular, large fruit' },
      { name: 'Onyx', maturityDays: 85, type: 'short', notes: 'Early, heat tolerant' },
      { name: 'Rio Grande', maturityDays: 95, type: 'medium', notes: 'Processing variety' },
      { name: 'Tengeru 97', maturityDays: 88, type: 'short', notes: 'Determinate, early' },
    ],
    stages: [
      { name: 'Nursery', startDay: 0, endDay: 21, description: 'Seedlings raised in nursery' },
      { name: 'Establishment', startDay: 22, endDay: 35, description: 'Transplant recovery' },
      { name: 'Vegetative', startDay: 36, endDay: 55, description: 'Rapid growth' },
      { name: 'Flowering', startDay: 56, endDay: 70, description: 'Flowers open' },
      { name: 'Fruit set', startDay: 71, endDay: 80, description: 'Fruits develop' },
      { name: 'Maturity', startDay: 81, endDay: 90, description: 'Fruits ripen' },
    ],
    weeklyActivities: [
      { week: 1, title: 'Nursery management', description: 'Water seedlings. Harden off before transplanting.', category: 'monitoring' },
      { week: 3, title: 'Transplant', description: 'Transplant at 3-4 true leaves. Water well.', category: 'monitoring' },
      { week: 4, title: 'Staking', description: 'Stake indeterminate varieties. Prune suckers.', category: 'weeding' },
      { week: 5, title: 'First weeding', description: 'Hand weed. Mulch to retain moisture.', category: 'weeding' },
      { week: 6, title: 'Top dress', description: 'Apply CAN/NPK at flowering.', category: 'fertilizer' },
      { week: 7, title: 'Scout for blight', description: 'Look for early/late blight. Spray fungicide.', category: 'pest' },
      { week: 8, title: 'Scout for whitefly', description: 'Check for whitefly and TYLCV.', category: 'pest' },
      { week: 10, title: 'Scout for fruit borers', description: 'Check for fruit borer damage.', category: 'pest' },
      { week: 12, title: 'Harvest', description: 'Harvest at breaker stage. Grade and pack.', category: 'harvest' },
    ],
  },
];

export const MONTH_TO_NUM: Record<string, number> = {
  Jan: 0, Feb: 1, Mar: 2, Apr: 3, May: 4, Jun: 5,
  Jul: 6, Aug: 7, Sep: 8, Oct: 9, Nov: 10, Dec: 11,
};

export function getCounty(name: string): County | undefined {
  return COUNTIES.find((c) => c.name.toLowerCase() === name.toLowerCase());
}

export function getCrop(name: string): CropInfo | undefined {
  return CROPS.find((c) => c.name.toLowerCase() === name.toLowerCase());
}
