/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#0d631b',
        'primary-container': '#2e7d32',
        'on-primary': '#ffffff',
        'on-primary-container': '#cbffc2',
        'primary-fixed': '#a3f69c',
        'primary-fixed-dim': '#88d982',
        'inverse-primary': '#88d982',
        secondary: '#2a6b2c',
        'secondary-container': '#acf4a4',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#307231',
        'secondary-fixed': '#acf4a4',
        'secondary-fixed-dim': '#91d78a',
        tertiary: '#704d40',
        'tertiary-container': '#8b6557',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffeee8',
        'tertiary-fixed': '#ffdbcf',
        'tertiary-fixed-dim': '#ebbcac',
        surface: '#faf9f5',
        background: '#faf9f5',
        'surface-dim': '#dadad6',
        'surface-bright': '#faf9f5',
        'surface-container': '#eeeeea',
        'surface-container-low': '#f4f4f0',
        'surface-container-high': '#e8e8e4',
        'surface-container-highest': '#e2e3df',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e2e3df',
        'surface-tint': '#1b6d24',
        'on-surface': '#1a1c1a',
        'on-surface-variant': '#40493d',
        'on-background': '#1a1c1a',
        outline: '#707a6c',
        'outline-variant': '#bfcaba',
        'inverse-surface': '#2f312e',
        'inverse-on-surface': '#f1f1ed',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      spacing: {
        'gutter-mobile': '16px',
        'margin-mobile': '20px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        base: '8px',
        lg: '40px',
        xl: '64px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
